### ISSUE TITLE
Fix lyric injection problem

### ISSUE THREAD

**Issue by swapnilraj** [JorikSchellekens/lyricist#1]
This bug also relates to the bug where the lyrics are not loaded on tab change.

**Comment by JorikSchellekens** [comment]
We're going to change to Mutation Observers. That should fix the problem. Except that it'll introduce an edge case when the page is first loaded. Since I've talked to you about this already we've decided to cache the events and ignore repeats which occur under 5ms from the next.

See the full solution sketch [in this gist](https://gist.github.com/JorikSchellekens/03bdcab7a7bccb714ba23da59c0fe67c).
PR coming mate.

**Comment by JorikSchellekens** [comment]
Pull request closes issue.
